#controllers:
#    resource: ../../src/Controller/
#    type: annotation
#Agrego desde acá
web_controller:
    resource: ../../src/Controller/Web/
    type: annotation
rest_controller:
    resource: ../../src/Controller/Rest/
    type: annotation
    prefix: /api
#Hasta acá
kernel:
    resource: ../../src/Kernel.php
    type: annotation


    